apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring
spec:
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
  - name: metricsport
    port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-example
